# -*- coding: utf-8 -*-
"""firstlab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/100G02ZcGTbcfZhOIPvePoWZhv72jUVGa
"""

name=str(input("enter the name:"))
month=float(input("month salary:"))
perday=float(month/26)
days=float(input("number of days:"))
sal=float(month*(50/100))
bs=int(perday*days-sal)
print("basic salary:", bs)
da=float(month*0.09)
hra=float(month+0.05)
ta=float(month+0.04)
pf=float(sal*0.15)
gp=int(sal+da+hra+ta)
np=int(gp+(bs-pf))
print("gross pay:", gp)
print("net pay:", np)

for i in range (0,1001,2):
  print(i)